### ISSUE TITLE
Using a caching layer

### ISSUE THREAD

**Issue by douglaslassance** [gtalarico/airtable-python-wrapper#102]
This is more a question than an issue, but did you think using something like [request-cache](https://pypi.org/project/requests-cache/)?

**Comment by gtalarico** [comment]
that interesting. wonder if it's possible to use without major changes to lib... 🤔 
also for run time caching, wrapping get calls in functools.lru_cache

**Comment by gtalarico** [comment]
In the meantime my suggestion is to wrap these calls on in a class and implement your own caching. I use lru_cache on mine:

eg.

``` 
class Contacts:

    def __init__(self, ...):...
        self.airtable = Airtable(....)
        
    @lru_cache
    def get_contacts(self, ...):
         self.airtable.get(....)
```

**Comment by gtalarico** [comment]
This is a nice idea but won't be implementing this in the near team.
Happy to consider an alternative implementation if someone wants to propose a design

**Comment by tedmiston** [comment]
[cachetools][1] is nice as well for the use case of "i want to cache these records for x minutes".  i don't think `functools.lru_cache` has built-in support for TTLs like this.

[1]: https://github.com/tkem/cachetools
