### ISSUE TITLE
what to enter when the date time field is NoneType 

### ISSUE THREAD

**Issue by Sree-NJ** [gtalarico/airtable-python-wrapper#103]
Nonetype or blank dates are not getting entered into Airtable. 
It shows Invalid Column Value. 

if d[11] != None:
        CarrierTimeStamp_New = d[11].isoformat()
    else:
        CarrierTimeStamp_New = ????

**Comment by Sree-NJ** [comment]
Fixed this by passing None. - 

if d[11] != None:
CarrierTimeStamp_New = d[11].isoformat()
else:
CarrierTimeStamp_New = None

Thank You.

**Comment by gtalarico** [comment]
Thanks for updating the issue, I will close it but feel free to follow up
Did you try empty string as well?`""`
Just curious...
