### ISSUE TITLE
More complex matching?

### ISSUE THREAD

**Issue by danmurphy1217** [gtalarico/airtable-python-wrapper#104]
@gtalarico, I could see a potential use case for more complex matching (for example, pass a list of field names and a list [of equal length] of field values and return the first cell ID that matches). Does this seem like a feasible feature to add? If so, happy to look into it.

**Comment by gtalarico** [comment]
Hey @danmurphy1217 
I haven't tried it, but are you able to achieve this using a formula?
```
>>> airtable.get_all(formula="FIND('SomeSubText', {COLUMN_STR})=1")
```
Thread:
https://community.airtable.com/t/search-for-multiple-strings/24776

> Does this seem like a feasible feature to add?
I wouldn't have time to work on this, but happy to merge a PR if we can come up with a simple design for it.
But we should discuss what the API might look like first as it could get complicated. 
Your example would be a list of OR key-value pairs. Would it also support AND?

> field names and a list [of equal length] of field values and return the first cell ID that matches)
What about using a dict for atrr and value instead?

**Comment by danmurphy1217** [comment]
> Hey @danmurphy1217
> I haven't tried it, but are you able to achieve this using a formula?
> 
> ```
> >>> airtable.get_all(formula="FIND('SomeSubText', {COLUMN_STR})=1")
> ```
> 
> Thread:
> https://community.airtable.com/t/search-for-multiple-strings/24776
> 
Hey @gtalarico, 
Haven't tried this, but it seems like it could be useful. Providing some more context on my specific use case: I was using `.match()` to retrieve a record ID and then `.update()` to update a column corresponding with that record ID. Pretty similar to the use case in the docs:
```PYTHON
>>> record = airtable.match('Employee Id', 'DD13332454')
>>> fields = {'Status': 'Fired'}
>>> airtable.update(record['id'], fields)
```
The match kept returning the wrong record ID since I was dealing with non-unique data points. I was thinking about adding additional functionality to the `.match()` method (or creating an entirely new method) that accepted more complex logic. 
> > Does this seem like a feasible feature to add?
> 
> I wouldn't have time to work on this, but happy to merge a PR if we can come up with a simple design for it.
> But we should discuss what the API might look like first as it could get complicated.
> Your example would be a list of OR key-value pairs. Would it also support AND?
> 
> > field names and a list [of equal length] of field values and return the first cell ID that matches)
> 
> What about using a dict for atrr and value instead?

Yes, I think using a dict would be a much better approach. My thoughts are to create a new method that accepts an `and` and `or` params. Each of these params accepts a dictionary of key-value pairs (each key is a column name, each value is the value to search for). It seems like this logic could then be parsed and specified in the `airtable.get_all(formula={})` request that is sent under-the-hood. Thoughts?

**Comment by gtalarico** [comment]
#126 will included for dict matching and utilities for composing formulas
Wip docs:
https://airtable-python-wrapper.readthedocs.io/en/version-2/api.html#pyairtable.formulas.match
