### ISSUE TITLE
ModuleNotFoundError: No module named 'Airtable'

### ISSUE THREAD

**Issue by ladakgit** [gtalarico/airtable-python-wrapper#108]
Hello,

I ran the pip install airtable-python-wrapper with success on my windows laptop. In my Jupyter I tried in importing two ways but got the modulenotfound error. Any clues?

Tried this first...
from airtable import Airtable

Tried this next
from airtable.airtable import Airtable

Thanks.

**Comment by gtalarico** [comment]
Is your source code file named airtable.py ?

**Comment by f2acode** [comment]
You can try run `!pip install airtable-python-wrapper` on a cell.

**Comment by gtalarico** [comment]
We have gotten several issue like this.
You probably have a me clash (file or folder named 'airtable')

**Comment by gtalarico** [comment]
Good candidate for FAQ - there have been [a few ](https://github.com/gtalarico/airtable-python-wrapper/issues?q=ModuleNotFoundError)of these `ModuleNotFoundError`
https://github.com/gtalarico/airtable-python-wrapper/issues/74
