### ISSUE TITLE
How to pass current datetime inn airtable

### ISSUE THREAD

**Issue by Rahulsharma0810** [gtalarico/airtable-python-wrapper#110]
The table looks like this 

![image](https://user-images.githubusercontent.com/9934859/107128205-e858dc00-68e1-11eb-96ce-cb7e3c111440.png)

I am trying to parse `datetime.now().strftime("%d %B %Y %H:%M %p" )` But airtable always show me 6.30 hours back from my timezone.

Can you guys give me an example for the current timezone feed?

**Comment by gtalarico** [comment]
@Rahulsharma0810 did you result this?

I would checking the Airtabe Api Docs and forum since this library does not case or format data for you at this time
https://github.com/gtalarico/airtable-python-wrapper/issues?q=ModuleNotFoundError
