### ISSUE TITLE
batch_update does not seem to exist

### ISSUE THREAD

**Issue by RogerTangos** [gtalarico/airtable-python-wrapper#112]
In the docs, the method `batch_update` is [referenced](https://airtable-python-wrapper.readthedocs.io/en/master/api.html?highlight=batch_update#airtable.Airtable.batch_update).

Unfortunately, it just doesn't seem to exist in the 0.15.1 `airtable-python-wrapper` package. That's off, since the code is in the repo.

```
dir(airtable)

> ...
  'batch_delete',
 'batch_insert',
 'delete',
 'delete_by_field',
 'get',
 'get_all',
 'get_iter',
 'insert',
 'match',
 'record_url',
 'replace',
 'replace_by_field',
 'search',
 'session',
 'table_name',
 'timeout',
 'update',
 'update_by_field',
 'url_table']
```

```
airtable.batch_update()

> 'Airtable' object has no attribute 'batch_update'
```

**Comment by gtalarico** [comment]
Can you try updating to 15.1?
https://github.com/gtalarico/airtable-python-wrapper/blob/master/HISTORY.md#0152

**Comment by RogerTangos** [comment]
I'm sorry for taking so long to get back to you. This is tested and fixed.
