### ISSUE TITLE
Do we need to close request.sessions underlying each instance of Airtable()?

### ISSUE THREAD

**Issue by ividrevich** [gtalarico/airtable-python-wrapper#113]
is there a way to manage/close underlying request.sessions for each instance of Airtable?  or is that done automatically behind the scene?  

If Im using Airtable() as part of an API backend which (running FastAPI) is used to connect front-end to AirTable -- do I need to do anything to clean up sessions that are opened with each new instance of Airtable()?

**Comment by gtalarico** [comment]
You can manipulate the session object directly however there is no persitent connection.
Session object from requests is just used to set all request params and authentication in one place
https://github.com/gtalarico/airtable-python-wrapper/blob/master/airtable/airtable.py#L135
