### ISSUE TITLE
Returning most recent records

### ISSUE THREAD

**Issue by am-berry** [gtalarico/airtable-python-wrapper#116]
Hey, thanks for this great package.

As I understand it, `get_all()` returns the first `max_records` number of records. Is there a way to let it return the most recently added entries (or alternatively, just the tail `n` entries of the table)?

**Comment by am-berry** [comment]
Just writing out the method I used to sidestep this for posterity; I'll let the maintainer(s) close the issue depending on what they feel is necessary.

1. Added another column to the airtable which has a Unix timestamp
2. Created another view that sorts by that column
3. `get_all(view=new_view, max_records=1)` to get the single most recent record.

**Comment by alan1world** [comment]
You can call a sort on the `get_all`:

```
table.get_all(maxRecords=2, sort=[('id', 'desc')])

```

Taken from [docs: Sort Param](https://airtable-python-wrapper.readthedocs.io/en/master/params.html#airtable.params.AirtableParams.SortParam)

**Comment by gtalarico** [comment]
Thanks for helping answer this @alan1world
