### ISSUE TITLE
Canonical way to delete all records in a table

### ISSUE THREAD

**Issue by alan1world** [gtalarico/airtable-python-wrapper#118]
What's the canonical way to delete all records in a table?

I've tried getting a list of all the ID and passing the list to `batch_delete`. This usually works, occasionally I get a 422 error:

> message\': \'"records" must be an array of up to 10 record IDs.

I think it's occurring when `batch_delete` is only being passed one record ID.  Does this mean I should call the single-record delete for every ID instead?

**Comment by gtalarico** [comment]
based on the message you post, sounds like there is a 10 record limit.
Are you sending more than 10?

**Comment by alan1world** [comment]
It's almost the opposite.

`batch_delete(record_ids)` [documentation](https://airtable-python-wrapper.readthedocs.io/en/master/api.html#airtable.Airtable.batch_delete) says: 

>Breaks records into batches of 10 and deletes in batches, following set API Rate Limit (5/sec). 

(This is to make it fit the REST API functionality mentioned)

_Here's an example:_ Say I have a table with 271 records. I fetch all the ID values using `get_all()` and pass the ID values to `batch_delete`. They will be broken into batches of 10, and deleted from the table successfully, until one - and only one - record is left. Then the process will raise an exception. Checking the airtable manually in the browser, I see that I have one record left in the table.

The API documentation says: 

> To delete links records, issue a DELETE request to the links endpoint.  
> Your request should include a URL-encoded array of up to 10 record IDs to delete.  
> You can also issue a DELETE request to the record endpoint to delete a single record.

The wrapper code says

```
def batch_delete(self, record_ids):

...

    response = self._delete_batch(chunk)

...

 def _delete_batch(self, record_ids):
    if len(record_ids) == 1:
       return self.delete(record_ids[0])
    return self._request("delete", self.url_table, params={"records": record_ids})

def delete(self, record_id):
    record_url = self.record_url(record_id)
   return self._delete(record_url)

def _delete(self, url):
    return self._request("delete", url)
```

What happening here is the wrapper will break the record list down into batches of 10, send them as an array of 10, until it gets to a reminder of 1, then it switches to deleting by endpoint rather than send an array of a single records. I'm not sure why it's doing this - either method **should** work because the documentation says you can send an array or a single endpoint.

My first read of it is that the endpoint is incorrectly formed when it transfers over the to the single-record delete. With the batch-mode, the code sends both the Table ID and the Record ID. In single-mode, the code should send an endpoint url. Note that if I _manually_ delete only one record, this works, and my code is almost identical to the wrapper code (`if len(records_to_delete) == 1: table.delete(records_to_delete[0])`. So not sure why the batch-mode switchover would fail?

**Comment by gtalarico** [comment]
This code was re-written in #126 
I think the new version uses batch even on the last record, which I think it's ok as long as API doesnt complain about it
