### ISSUE TITLE
Cannot insert record with "Link" type field

### ISSUE THREAD

**Issue by kingychiu** [gtalarico/airtable-python-wrapper#12]
I tried to insert the following record but it threw an error. It works when I remove the User ID field. The User ID is referencing another table.

```
payload = { 
            'Website ID': str(website.get_wid()),
            'Title': str(website.get_title()),
            'URL': str(website.get_url()),
            'User ID': [str(user.get_uid())]
}
```

The official documentation suggests I should post an array of string:

`EXAMPLE VALUE
["rec8116cdd76088af", "rec245db9343f55e8", "rec4f3bade67ff565"]`

**Comment by gtalarico** [comment]
Hi @kingychiu 
I wrote a quick test and it seems to be working as expected here:

![image](https://user-images.githubusercontent.com/9513968/32498302-58df9812-c39d-11e7-831d-1c93b00e857f.png)

Maybe try posting a larger code sample or the more info on  the error?

**Comment by kingychiu** [comment]
It was my faullt, I put an Array of user id, but I should put an Array of record id instead. Thank you very much for this code base.

**Comment by gtalarico** [comment]
You are welcome, glad you got it working
