### ISSUE TITLE
requests.exceptions.HTTPError

### ISSUE THREAD

**Issue by Tylm01** [gtalarico/airtable-python-wrapper#121]
I want to get access to my database but I have an 404 Client error.
The goood url seems to be 
https://api.airtable.com/v0/base_id/Imported%20table?api_key=API_key
When I use this link above, my datas displays directly in my browser!

but currently, when I launch my script to get my datas, it uses the url below:

https://api.airtable.com/v0/base_id/name_id

my script 👍 

    key=API_KEY
    table_name=TABLE_NAME
    base_key=ID_BASE
    airtabl = Airtable(base_key, table_name, key)
    records=airtabl.get_all()
    print(records)

**Comment by gtalarico** [comment]
Are you using the display or escaped table name?
https://github.com/gtalarico/airtable-python-wrapper/issues/34#issuecomment-495742393

**Comment by Tylm01** [comment]
could you give me the difference ? As TABLE_NAME I use 20210701.csv

**Comment by Tylm01** [comment]
![screenshot-airtable com-2021 07 02-20_15_50](https://user-images.githubusercontent.com/86857702/124337807-6b6d1e00-db72-11eb-9ca5-28f26c62f166.png)

**Comment by gtalarico** [comment]
Please read thread I linked above.
Your table name is likely getting double encoded.
If your table name is 'Imported Table' the library will encode to url safe 'Imported%20Table'
If you provided the encoded name it will get double encoded

**Comment by Tylm01** [comment]
Thanks Gtalarico but it does not work with my table, and I just saw in the documentation REST API for my table, the good url to get access to it is : 
https://api.airtable.com/v0/appGagpsqZonIT9aF/Imported%20table?api_key=YOUR_API_KEY
And when I use this url directly in my browser I see all my datas.

**Comment by Tylm01** [comment]
Gtalarico I get the solution, I use the Airtable Api encoder on Codepen.io and I used the table name given by airtable api and it works.

**Comment by gtalarico** [comment]
Thanks for reporting back but in the future please include all code needed to reproduce issue or detailed traceback.
Table name works as expected so if you are getting a 404 most likely you are double encoding the table name as shown below.

```python 
>>> import os
>>> from airtable import Airtable

>>> # URL
>>> # https://api.airtable.com/v0/appu15p8579gOPqm7/test%20table?maxRecords=3&view=Grid%20view

>>> table = Airtable("appu15p8579gOPqm7", "test table", api_key=os.environ["AIRTABLE_API_KEY"])
>>>print(table.get_all())
[{'id': 'recP6SdMCGZOGyTTg', 'fields': {'Name': 'Test', 'Notes': 'Test'}, 'createdTime': '2021-07-04T18:57:46.000Z'}]

>>> print(table.url_table)
https://api.airtable.com/v0/appu15p8579gOPqm7/test%20table
```

```
>>> table = Airtable("appu15p8579gOPqm7", "test%20table", api_key=os.environ["AIRTABLE_API_KEY"])
>>> print(table.get_all())
requests.exceptions.HTTPError: ('404 Client Error: Not Found for url: https://api.airtable.com/v0/appu15p8579gOPqm7/test%2520table', "404 Client Error: Not Found for url: https://api.airtable.com/v0/appu15p8579gOPqm7/test%2520table [Error: {'type': 'TABLE_NOT_FOUND', 'message': 'Could not find table test%20table in application appu15p8579gOPqm7'}]")


>>> print(table.url_table) # notice douple enconding of space character
https://api.airtable.com/v0/appu15p8579gOPqm7/test%2520table
```

**Comment by wanghaisheng** [comment]
@gtalarico  do i need manually create in airtable to get this url?
>>> # https://api.airtable.com/v0/appu15p8579gOPqm7/test%20table?maxRecords=3&view=Grid%20view

```
    api = Api(os.environ['AIRTABLE_API_KEY'])

    base = Base(apikey, 'test')

    table = Table(apikey, 'test', 'test')
```
i got 404 here
