### ISSUE TITLE
Deploying on lambda > 'airtable object has no attribute 'get_iter'

### ISSUE THREAD

**Issue by vtennero** [gtalarico/airtable-python-wrapper#124]
Hi, 

When deploying on lambda, I get the following error

It would seem there is a conflict between airtable and airtable-python-wrapper but I don't know how to solve it.

error log:
```
  "errorMessage": "'Airtable' object has no attribute 'get_iter'",
  "errorType": "AttributeError",
```
In my lambda_function.py:
```
from airtable import Airtable 
...
table_output = Airtable(base_key, output_table_name, apikey)
output_pages = table_output.get_iter(view='Grid view')
...
table_output.insert({'abc':x.y})
```
In my root folder of my lambda:
```
airtable
airtable-0.4.8.dist-info
...
lambda_function.py
...
requirements.txt
```
In my requirements.txt:
```
airtable-python-wrapper
airtable
```

Note: with lambda, dependencies need to be uploaded in the same .zip as the main function for the app to run with its dependencies.

Thank you for your help

**Comment by k-dal** [comment]
It looks like this is happening because you're including `airtable` instead of `airtable-python-wrapper` in your root directory. They're completely separate libraries ([airtable](https://github.com/josephbestjames/airtable.py) and [airtable-python-wrapper](https://github.com/gtalarico/airtable-python-wrapper)) with similar functionality -- though I think this one is _significantly_ better. It's also not clear why both are in your requirements.txt, but only `airtable` is in your root dir.

Is there a reason you need both of them? Why not stick to `airtable-python-wrapper`?

**Comment by vtennero** [comment]
thank you. I thought airtable-python-wrapper needed the airtable library.

1. If I stick to airtable-python-wrapper, should I just clone the github repo, upload it together with lambda?
2. How do I import it since python does not support folder import with '-' in names?
Thanks for your help

**Comment by gtalarico** [comment]
> How do I import airtable-python-wrapper in the main python file

the pypi package name is `airtable-python-wrapper` but the importable package name is `airtable`.
Unfortunately this is confusing but not uncommon.


For #1 I would search for how ways to  include/bundle python packages in lambda deployment eg. 
[aws docs](https://docs.aws.amazon.com/pinpoint/latest/developerguide/tutorials-importing-data-create-python-package.html).

**Comment by vtennero** [comment]
thank you, got it.


error log:
```
{
  "errorMessage": "Unable to import module 'lambda_function': No module named 'airtable'",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}
```
In my lambda_function.py:
```
from airtable import Airtable 
...
table_output = Airtable(base_key, output_table_name, apikey)
output_pages = table_output.get_iter(view='Grid view')
...
table_output.insert({'abc':x.y})
```
In my root folder of my lambda:
```
airtable-python-wrapper
...
lambda_function.py
...
requirements.txt
```
In my requirements.txt:
```
airtable-python-wrapper

```

Thank you for your help

**Comment by gtalarico** [comment]
@vtennero I would like to be able to help but I am not an expert in AWS lambdas and this appears to be a general issue with lambda python dependencies or python runtime, but not specific about this library functionality.

A stackoverflow question with tags for `python`, `aws`, `lambda` etc would be better suited for this type of question/discussion.

**Comment by vtennero** [comment]
thanks, all sorted with the following:
In my lambda_function.py:
```
from airtable import Airtable 
```
In my root folder of my lambda:
```
airtable -> folder inside airtable-python-wrapper
...
lambda_function.py
...
requirements.txt
```
In my requirements.txt:
```
airtable-python-wrapper
```
