### ISSUE TITLE
update entire table with new records information

### ISSUE THREAD

**Issue by bgriffen** [gtalarico/airtable-python-wrapper#14]
It would be great if you could just provide all the records and update the entire table.

```
records = airtable.get_all()
records[1]['fields']['Status']) = 'Updated'
airtable.update_all(records)
```

This is particularly useful if you say have a csv file you've loaded as a dataframe from an external database and you want to populate/update the Airtable.

**Comment by gtalarico** [comment]
Hi bgriffen 
Regardless of the library, the Api only can only update one record at the time.
Thia can easily be accomplished with a simple for loop and the airtable.update method (will only update included fields)
