### ISSUE TITLE
serach or get_all case insensitive lookup

### ISSUE THREAD

**Issue by s2krish** [gtalarico/airtable-python-wrapper#15]
Hello,

I wonder if there's case insensitive lookup for `get_all` or `search` method.

     AT.get_all(formula="FIND('John', {Name})")

This query returns record that has name **John** but not **john**. How can I get **john**, **John**, **jOhn**, .... **johN**.

**Comment by gtalarico** [comment]
Could you use the text operator LOWER? and compare it to 'john' 

https://support.airtable.com/hc/en-us/articles/203255215-Formula-field-reference#text

**Comment by s2krish** [comment]
Wonder what would be syntax. Is this like:

     AT.get_all(formula="FIND('john', LOWER({Name}))")

**Comment by gtalarico** [comment]
Yes. That should work

![image](https://user-images.githubusercontent.com/9513968/34997449-8b68bfea-faaa-11e7-9f05-2311ee0c4aa6.png)

![image](https://user-images.githubusercontent.com/9513968/34997431-8460c0e4-faaa-11e7-8c8f-46ff9e2c25a0.png)
