### ISSUE TITLE
Exceptions on insert could be more helpful

### ISSUE THREAD

**Issue by kbakk** [gtalarico/airtable-python-wrapper#16]
If you use insert a string to an integer field in Airtable, or insert to a field which doesn't exist, an error will be thrown:

```
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/<your base id>/<your table name>
```

I notice that Airtable provides a more helpful message in the response body, which could be returned: 

```json
{
  "error": {
    "type": "INVALID_VALUE_FOR_COLUMN",
    "message": "Field Integer_Field can not accept value 113034809"
  }
}
``` 

One way of handling this could be to catch HTTP errors, and if it converts to JSON, get the error and print this. I've implemented it like this for now:

```python
try:
    result = at.insert({'Integer_Field': '113034809'})
except requests.exceptions.HTTPError as err:
    import json
    try:
        error_object = err.response.json().get('error', {})
        msg = (error_object.get('type', 'UNKNOWN TYPE') + ": " +
               error_object.get('message', err.response.text))
        raise ValueError(msg)
    except json.decoder.JSONDecodeError:
        raise Exception(err)
```

I think it would be nice if the error type+message could be raised airtable-python-wrapper.

**Comment by kbakk** [comment]
@gtalarico If you're interested, I would like to see if I can submit a PR for this. Note - I am a beginner, but please let me know.

**Comment by gtalarico** [comment]
This is a great suggestion. 
I am not sure if I missed the fact the error message was in the 422 responses, or if they were added after I wrote the wrapper.

This seems like it could also be a reasonable solution:
https://github.com/kevin1024/vcrpy

**Comment by gtalarico** [comment]
Added to '0.9.1' @kbakk 
Let me know if it works for you

https://github.com/gtalarico/airtable-python-wrapper/commit/97b757d524fcd245fe3c920004fc01c8697f63d0

Test:
https://github.com/gtalarico/airtable-python-wrapper/commit/8a085d3cf43393c6219b2248f1c85e5c48c85bed
