### ISSUE TITLE
Failed to search records based on a Date field

### ISSUE THREAD

**Issue by raymond-alphalex** [gtalarico/airtable-python-wrapper#22]
When I try to search records based on a Date field, it returns an empty list.

`table.search('Position Date', '2018-05-31')`

**Comment by raymond-alphalex** [comment]
Sorry it seems my "fix" only caused it to return all records.

Still, there is no way to search records based on a Date field.

**Comment by gtalarico** [comment]
You are right. the search builds a simple formula to compare, but for datetime types the formula needs to be different. If you are trying to compare simple dates, something like this should work:

`airtable.get_all(formula='DATETIME_DIFF({COLUMN_NAME}, "YYYY-MM-DD")=0')`
or
`airtable.get_all(formula='DATETIME_DIFF({StartDate}, "2018-04-23")=0')`
