### ISSUE TITLE
GitHub/PyPi Release Incongruence / Missing HISTORY.MD in 11.2

### ISSUE THREAD

**Issue by bmcguirk** [gtalarico/airtable-python-wrapper#23]
Hi there - 

Just wondering - the latest release on here (GitHub) is `10.0.1`. The latest release on [PyPi](https://pypi.org/project/airtable-python-wrapper/) is [`11.2`](https://pypi.org/project/airtable-python-wrapper/0.11.2/). 

Just noticed this because HISTORY.md is missing from 11.2, but is found here. The lack of it caused my `conda skeleton pypi airtable-python-wrapper` to fail. 

Is 11.2 maintained somewhere else?

**Comment by gtalarico** [comment]
Looks like I had a bit of a mess on my tags
Should be clean now and `0.11.2` is the latest release tag, matching the latest pypi release

**Comment by bmcguirk** [comment]
Hey sorry but I think there's still a bit of an incongruency. Setup.py fails every time, because the package hosted at PyPi (`0.11.2`) doesn't have a HISTORY.md. 

```Python
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    with open('HISTORY.md', mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
```

Your code on the master branch works, but it's just not the same as PyPi. Sorry - just would like to use / potentially contribute to this module, here.

**Comment by gtalarico** [comment]
I think I need to explicitly add those files to my setup.py so they get included in the pypi release.
I will see if I can fix that.

But in the meantime, you can get the source directly from this repo, 
which is more common than pulling from the pypi release.

* To install, directly from pypi
`pip install airtable-python-wrapper`

* To use it locally/develop:
```
git clone git@github.com:gtalarico/airtable-python-wrapper.git
cd airtable-python-wrapper
```

Install
```
pip install -e . 
# or 
python setup.py develop
```

**Comment by gtalarico** [comment]
Should be fixed on the latest release if you want to install from pypi release source
