### ISSUE TITLE
'Airtable' object has no attribute 'get_all'

### ISSUE THREAD

**Issue by jkoseattle** [gtalarico/airtable-python-wrapper#24]
I am receiving the error in the Title when trying to run my Python within a cron job. I have been having trouble getting the module to even be recognized, I finally came up with
`from airtable import airtable`
and then instantiating objects with 
`airtable.Airtable(...`
Not sure why I had to change that for the cron job, it used to just say
`from airtable import Airtable `
but anyway, now I can instantiate the object, but I'm getting the title error when I run
```
monitor_table = airtable.Airtable(MY_BASE_KEY, 'monitor')
monitor_recs = monitor_table.get_all()
```
I've tried reinstalling airtable-python-wrapper. What is going on? This all worked fine before trying to run from the cron job.

**Comment by gtalarico** [comment]
`from airtable import Airtable` should work fine and tests are passing. 
I would need more info to be able to help. 

What python version are you using?
Did you install it using pip?
Are you using a virtual environment?

**Comment by qwertyuu** [comment]
@jkoseattle 
You have 2 choices

Either
```python
from airtable import Airtable
monitor_table = Airtable(MY_BASE_KEY, 'monitor')
```

**OR**

```python
import airtable
monitor_table = airtable.Airtable(MY_BASE_KEY, 'monitor')
```

You cannot mix *both*, that is, if you import airtable from airtable, you already have direct access to the Airtable class.

**Comment by LelandFowler** [comment]
This seemed to be a problem with venv in pycharm. I noticed that when I change my interpretor or venv I get this error (had been trying to use the poetry 3.10.2 rips of python)
