### ISSUE TITLE
Character character limit on "Long Text"

### ISSUE THREAD

**Issue by JWDT** [gtalarico/airtable-python-wrapper#26]
This is related to #16 but for Long Text type fields there is a (barely documented) limit of 100,000 characters.

I've got around this by just truncating the things I'm uploading (as it works for this use case).

`new_log = str(new_log + log_notes)[-80000:]`

Don't know if the best action would be to just document it somewhere, or possibly provide an option to automatically trim things so they fit.

(Great module by the way, really appreciate it!)

**Comment by gtalarico** [comment]
Thanks for the comment.
I don't like the idea of automatically truncating it, 
but maybe it could throw a type error if string is longer than allowed.

I don't have the time to implement this now but would be happy to merge a pr for it.

**Comment by JWDT** [comment]
I'm working on some things with this at the moment, I'll see what I can sort out if I have a chance. :-)

**Comment by gtalarico** [comment]
No rush, entirely up to you :)
