### ISSUE TITLE
API rate limit documentation

### ISSUE THREAD

**Issue by widyono-cets** [gtalarico/airtable-python-wrapper#27]
I had to submit a support request to Airtable in order to discover that the API rate limit applies _per base_, **not** _per API KEY_. After that discovery I proposed documentation updates for them to clarify that.

Would you consider updating your docs as well to clarify that point for users of your wrapper? This affects teams with multiple collaborators on one base, all using the API concurrently, raising the potential for interfering with each other's API use and running afoul of the API rate limit even though each user thinks they are complying on their own.

To be precise: if API_KEY A and API_KEY B both access the same Base, A may attempt to make 5 requests in a second, and B may attempt to make 5 requests in the same second, and that would overflow the Base rate limit.

**Comment by gtalarico** [comment]
Hi and thanks for creating this issue.

I want to avoid duplicating docs of the API specs here, 
but this seems reasonable enough given that:
A. wrapper supports API rate config
B. the info is missing from the official docs

Happy to merge if you want to send a PR

https://github.com/gtalarico/airtable-python-wrapper/blob/9b3bc50f699d1e5afaeaf05e48406989970f7de3/airtable/airtable.py#L372
https://github.com/gtalarico/airtable-python-wrapper/blob/9b3bc50f699d1e5afaeaf05e48406989970f7de3/airtable/airtable.py#L380
https://github.com/gtalarico/airtable-python-wrapper/blob/9b3bc50f699d1e5afaeaf05e48406989970f7de3/airtable/airtable.py#L538

**Comment by gtalarico** [comment]
Working on building in Retry. Closing this

**Comment by gtalarico** [comment]
https://github.com/gtalarico/airtable-python-wrapper/pull/93
