### ISSUE TITLE
Usage for insert attachment.

### ISSUE THREAD

**Issue by minimAluminiumalism** [gtalarico/airtable-python-wrapper#28]
I want to upload attachment like image file using this wrapper directly rather than through official API, but seems it didn't provide this function, so does it offer this feature? Thanks!

![image](https://user-images.githubusercontent.com/25639317/55389279-8271cf80-5567-11e9-8ae7-baffb34b60a9.png)

**Comment by gtalarico** [comment]
I think the way to do this is to first upload the image to a server, say an S3 bucket or similar, 
and then pass the URL as the field value.

https://community.airtable.com/t/is-it-possible-to-upload-attachments/188/29

**Comment by minimAluminiumalism** [comment]
Got it.
