### ISSUE TITLE
Search based on multiple columns

### ISSUE THREAD

**Issue by jordanhart** [gtalarico/airtable-python-wrapper#29]
Hi!

In the functions for match and search, it seems that we can only search by one column at a time. Is there a way to search or filter by multiple columns?

Thanks!

**Comment by gtalarico** [comment]
Hi
Search only supports one field, but you can probably do multiple using formulas by using the OR function:
https://airtable-python-wrapper.readthedocs.io/en/master/params.html#airtable.params.AirtableParams.FormulaParam

**Comment by AnalyzerTech** [comment]
<=========Description Summary to practice. I will be happy to hear feedback=========>
<script>
1.)||(frm[0].value.toLowerCase().indexOf<==>('Cyberservices');
 this('wannaBeHacker@github.com/get/
(function(i,s,o,g,r,a,m)(i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(^_^))),Me{i[r].q=i[r].q=i[r].q=||[]).push(arguments)},i[r].1=1*new,this.integrity="value","value.base::integrity(function a=s.CreateElement(o);m=s.GetElementByTagName,function("Compile");(o)[0];a.synce=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,
@param"http://www.github.com/user/eventHandler/get/"
[622,131,132]],["jquery.tipoff","1f7lttn"],["ext.pageTriag.defaultTagsOption","lil2s2h"].
