### ISSUE TITLE
How to search in view ? 

### ISSUE THREAD

**Issue by Aarbel** [gtalarico/airtable-python-wrapper#31]
```PY
airtable = Airtable('BaseName', 'TableName', api_key='dfldndljndl')
records = airtable.search('Email', email, view='Authenticator')
```
@gtalarico i would like to perform a search in a Table View, but this code doesn't work, what's the best syntax ?

Thanks a lot for this lib !

**Comment by gtalarico** [comment]
Hi - can you expand on what you mean by  _doesn't work_ ?
No results? Error messages?

**Comment by Aarbel** [comment]
@gtalarico the "view" parameter is not supported by the .search method, as writtent in my example

**Comment by Aarbel** [comment]
I was just a tryout, my goal is just to search inside an AIrtable table view. No example shows the right way to do it in your documentation ;)

**Comment by gtalarico** [comment]
`seach()` should support `view` kwargs - if it doesn't then there is a bug.
As a work around you can get all and iterate your self or use a formula filter.
https://airtable-python-wrapper.readthedocs.io/en/master/params.html#airtable.params.AirtableParams.FormulaParam

**Comment by bpeterso2000** [comment]
Is this still an issue?

I was able to test this and validate that the `view` parameter works properly with `search`.  Would need to see the exact error message to proceed any further.

The syntax above is correct; however, if the `field_value` argument, i.e., `email` is not a string, it would cause a problem.

**Comment by Aarbel** [comment]
sorry didn't had the time to test again. Seems solved.
