### ISSUE TITLE
Authentication 404 Error

### ISSUE THREAD

**Issue by theopass** [gtalarico/airtable-python-wrapper#34]
This is my first submission, so apologies if I am just missing something obvious.

I believe the API_BASE_URL (https://api.airtable.com) has been changed recently to https://airtable.com/api, this is where I am redirected when typing in the url.

The only way I seem to be able to create and successfully authenticate an Airtable class is by removing the version variable from the url_table and by switching the API_BASE_URL to the one aforementioned.

Am I doing something wrong or have there been changes to the airtable API?

**Comment by theopass** [comment]
I believe I corrected myself, I restored everything back to normal. 

Turns out the only weird issue I had was when I used the url_safe_table_name for authentication it returned a 404, but using the table_name allowed me to create the Airtable class.

Is there something wrong with this approach?

**Comment by gtalarico** [comment]
I am sorry I don't understand the question. Can you include a code snippet?
`url_safe_table_name` is an internal local variable and does need to be touched.
I tested against one of the default bases and it seems to be working fine.

```python
>>> from airtable import Airtable
>>> table = Airtable(base_key='appEioitPbxI72w06', table_name='Editorial', api_key='keyMyKey')
>>> table.get_all()
[{'id': 'rec9B3nlOhIxUVX1e', 'fields': [... TRUNCATED]
>>> table.url_table
'https://api.airtable.com/v0/appEioitPbxI72w06/Editorial'
```

Note the generate url matches the documentation, minues the `api_key` which is added in the request headers instead of url query params

![image](https://user-images.githubusercontent.com/9513968/58345881-48f26d80-7e0e-11e9-92e6-bd9663c5f9b8.png)

**Comment by theopass** [comment]
When the table name includes characters such as % the safe_url changes the string slightly:

`>>> airtable = Airtable("appipCCmuh5ixrmxX","Content%20production")`
`Traceback (most recent call last):`
  `File "<stdin'>", line 1, in <module>`
 ` File "C:\Users\theom\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtable\airtable.py", line 131, in __init__`
 `   self.is_authenticated = self.validate_session(self.url_table)`
  `File "C:\Users\theom\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtable\airtable.py", line 138, in validate_session`
   ` raise ValueError('Invalid base or table name: {}'.format(url))`
`ValueError: Invalid base or table name: https://api.airtable.com/v0/appipCCmuh5ixrmxX/Content%2520production`

![image](https://user-images.githubusercontent.com/43299325/58346851-2706e400-7e2a-11e9-95d7-7e6015dd7eaf.png)

Am I missing something very obvious? Perhaps using the appropriate escape character?

**Comment by gtalarico** [comment]
auto url escape was added by a contributor on #10 
Did you try using the un-escaped version of the table name?
```
airtable = Airtable("appipCCmuh5ixrmxX","Content production")
```
should correctly result in the url below:
```
https://api.airtable.com/v0/appipCCmuh5ixrmxX/Content%20production
```

**Comment by theopass** [comment]
Ok, thanks a bunch!

Not to flock this issue with unrelated questions, but I noticed the airtable API doesn't allow for creating and reading comments. You haven't found a way to work around this, have you?

Again, thanks for all the help.

**Comment by gtalarico** [comment]
Not that I know of. I don't think thats exposed through the api

**Comment by Rahul11a** [comment]
I had the same bug.
Thanks for the help gtalarico.
