### ISSUE TITLE
Allow get_all without fields specified

### ISSUE THREAD

**Issue by mkirzon** [gtalarico/airtable-python-wrapper#41]
My use case is to retrieve a row count for a particular filter. Ideally, we want to send as lightweight as possible of a request. I currently include a single field with the smallest data size. The result set includes the record id, my requested field, and the create time. 

To improve this query performance further, it'd be helpful to send a request with no fields and return just the record id. For example, I'd like to call:
`airtbl_ppl.get_all(sort=['Name'], formula="{Import Status}=''", fields='')`

**Comment by gtalarico** [comment]
I don't the API supports empty fields filter. 
It returns a `422 Client Error: Unprocessable Entity` for any value that is not a valid field name.

**Comment by gtalarico** [comment]
Closing this since there is nothing the client library can do to help, but feel free to continue the conversation

**Comment by mkirzon** [comment]
> I don't the API supports empty fields filter.
> It returns a `422 Client Error: Unprocessable Entity` for any value that is not a valid field name.
> 
> A workaround would be to use just one of the columns, maybe the one with least data

Agreed this is the best solution. I ended up creating an empty hidden column.

**Comment by gtalarico** [comment]
Great thanks for the update!
