### ISSUE TITLE
Implement Get Filter

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/airtable-python-wrapper#5]

**Comment by b-nroths** [comment]
Is there a reason this wasn't added?  when I added via
`airtable._ALLOWED_PARAMS.append("filterByFormula")`
it worked, so I'm happy to test and add to the source if you would like.

Ben

**Comment by gtalarico** [comment]
I just haven't had time to test it and write tests and docs. 
Happy to take any prs

**Comment by gtalarico** [comment]
Added. Use kwarg formula
