### ISSUE TITLE
SystemError: The remote server returned an error: (422) Unprocessable Entity

### ISSUE THREAD

**Issue by saurabhsjha** [gtalarico/airtable-python-wrapper#56]
File "C:\Users\sjha\Documents\Python Scripts\india-dt-pyPlugins\WWI Tools.extension\WWI Tools.tab\lib\airtable\airtable.py", line 395, in insert
 File "C:\Users\sjha\Documents\Python Scripts\india-dt-pyPlugins\WWI Tools.extension\WWI Tools.tab\lib\airtable\airtable.py", line 239, in _post
 File "C:\Users\sjha\Documents\Python Scripts\india-dt-pyPlugins\WWI Tools.extension\WWI Tools.tab\lib\airtable\airtable.py", line 221, in _request
SystemError: The remote server returned an error: (422) Unprocessable Entity.

**Comment by gtalarico** [comment]
Can you include the request code?

**Comment by saurabhsjha** [comment]
![image](https://user-images.githubusercontent.com/16698814/61200785-373b9100-a700-11e9-857e-c35df27c6fbe.png)

**Comment by gtalarico** [comment]
This is just the error & traceback. You need to include the code with the call you are making.

**Comment by saurabhsjha** [comment]
[rest_script.txt](https://github.com/gtalarico/airtable-python-wrapper/files/3391560/rest_script.txt)

**Comment by saurabhsjha** [comment]
any comments

**Comment by gtalarico** [comment]
Hi @saurabhsjha - I am sorry but I don't have enough information to help you.

Please keep in mind this is an open source project and maintaining and supporting it is done on my free time. You should not expect me to have to read though hundreds of lines of code to help you troubleshoot it.

It would be helpful if you can pin down the exact arguments that are being passed to the request and create an [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by saurabhsjha** [comment]
@gtalarico I am sorry for the long lines of code.  i tried to make a minimal reproducible example please have a look
[Opsexport_script.txt](https://github.com/gtalarico/airtable-python-wrapper/files/3400206/Opsexport_script.txt)
sorry once again to keep brothering you.
![image](https://user-images.githubusercontent.com/16698814/61348077-f9b04280-a87c-11e9-8a80-638170e8945e.png)

**Comment by gtalarico** [comment]
Most likely the column's of the table you are pushing into doesn't match your payload
Make sure the table you are hitting has *all* the columns with the exact same name as in your dictionary (eg. `SPACE`, `8TH FLOOR`, `TERRACE FLOOR` etc).  

Here is an example, if I try to push a record to a column name that doesn't exist
```
airtable.insert({'somecolum': 1})
```
![image](https://user-images.githubusercontent.com/9513968/61689011-45c71100-acdb-11e9-96ae-d7252fba1e39.png)

Not sure why your the traceback is not including the full error msg.
