### ISSUE TITLE
Is Travis set up?

### ISSUE THREAD

**Issue by dargueta** [gtalarico/airtable-python-wrapper#58]
I made a fork and opened a PR but I don't see a Travis build despite the `.travis.yml` file. Is this repo not set up for it or something?

**Comment by gtalarico** [comment]
should be setup:
https://travis-ci.org/gtalarico/airtable-python-wrapper

**Comment by dargueta** [comment]
Oh, I see. I only saw the Coveralls badge -- didn't notice that there was a tiny link on the Coveralls page to the Travis build. Sorry about that.

**Comment by gtalarico** [comment]
np. "build|passing" badge is the travis link
![image](https://user-images.githubusercontent.com/9513968/63536842-495fda80-c4c9-11e9-8e2b-f005221cbfcb.png)

**Comment by dargueta** [comment]
It _is_ weird though that the build in my PR is passing even though the Python 2.7 and 3.5 builds failed on Travis.
