### ISSUE TITLE
Configurable Timeout in Requests

### ISSUE THREAD

**Issue by johruss** [gtalarico/airtable-python-wrapper#64]
Hello,

I have an unsteady internet connection, and I had to add timeout=(3,10) to line 170 to get it to kick up and not get paralysed.
If you read https://realpython.com/python-requests/#timeouts, you will say they say :
"When you make an inline request to an external service, your system will need to wait upon the response before moving on. If your application waits too long for that response, requests to your service could back up, your user experience could suffer, or your background jobs could hang.

By default, requests will wait indefinitely on the response, so you should almost always specify a timeout duration to prevent these things from happening. To set the request’s timeout, use the timeout parameter. timeout can be an integer or float representing the number of seconds to wait on a response before timing out:"

Please make this standard, it will save a lot of time to others.

**Comment by gtalarico** [comment]
Happy to merge a PR
