### ISSUE TITLE
JSONDecodeError does not exist in Python 2

### ISSUE THREAD

**Issue by jws325** [gtalarico/airtable-python-wrapper#67]
_process_response uses JSONDecodeError, which is not in Python 2.
This causes airtable to crash without printing the error correctly.

We can remedy this by doing something like:

try:
    from json.decoder import JSONDecodeError
except ImportError:
    JSONDecodeError = ValueError

Then in _process_response use JSONDecodeError  instead of json.decoder.JSONDecodeError

**Comment by gtalarico** [comment]
Fixed on #57
