### ISSUE TITLE
unable to push data from Mysql table to Airtable base. 

### ISSUE THREAD

**Issue by Sree-NJ** [gtalarico/airtable-python-wrapper#68]
![image](https://user-images.githubusercontent.com/59960222/74854490-69cbfd00-5365-11ea-8d2e-c98639b79804.png)

![image](https://user-images.githubusercontent.com/59960222/74854345-37ba9b00-5365-11ea-8025-a00563238c76.png)

HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/appWDY1nCpCqu51hZ/Drop-Ship Order Addresses - Test Case Example (Decoded URL) [Error: {'type': 'INVALID_VALUE_FOR_COLUMN', 'message': 'Value is not an array of record IDs.'}]

Please help here. !!

**Comment by gtalarico** [comment]
Erro message is pretty clear.
One of your columns is link type and is expecting a list of ids

**Comment by Sree-NJ** [comment]
Thanks @gtalarico  I figured it out, and removed the link in one of the columns and it worked !!!
Appreciate your quick response !!! You are awesome ! The big code, you made it in two lines technically speaking. Kudos !

**Comment by Sree-NJ** [comment]
Hi @gtalarico  : is there any way we can push data to a linked field ? Please advise.

**Comment by gtalarico** [comment]
You can update linked fields but you need to fetch records to know the record
