### ISSUE TITLE
Updating already existing records in Airtable. 

### ISSUE THREAD

**Issue by Sree-NJ** [gtalarico/airtable-python-wrapper#69]
Hi gtalarico,
How to update the already existing records in Airtable from Dataframe ?

![image](https://user-images.githubusercontent.com/59960222/75276530-4f45c800-582c-11ea-918f-860f65f4e56d.png)

**Comment by gtalarico** [comment]
You need to fetch the target records and get their id first. see docs
https://airtable-python-wrapper.readthedocs.io/en/master/api.html#airtable.Airtable.update
