### ISSUE TITLE
Search Param

### ISSUE THREAD

**Issue by samgdf** [gtalarico/airtable-python-wrapper#7]
How would I get the search result to be query-able?

In other words, let's say I have
`airtable.search('Name', str(List[i]))`, where i in that list is some name equivalent to some name in the airtable. I then would like to pull the information from that specific item in the airtable. I understand that search returns that, but how would I then capture specific portions, say, `data[i]['fields']['Location']` or similar?

Cheers!

**Comment by gtalarico** [comment]
Hi @samgdf 
This seems more like a python question/issue than a wrapper one, 
but here is what you could do:

```
results = airtable.search('State', 'NY')  
# search() always returns a list so you can just iterate through it
cities = [i['City'] for i in results['fields']]
```
