### ISSUE TITLE
Awesome job

### ISSUE THREAD

**Issue by KalobTaulien** [gtalarico/airtable-python-wrapper#79]
This package has helped me a lot this week and I really just wanted to show some appreciation. 

Thank you @gtalarico for putting in so much effort over the years! :) 

(Feel free to close the issue as it's actually not an issue and does nothing to contribute to the source)

**Comment by KalobTaulien** [comment]
Very nice! I'm currently creating a Wagtail/Airtable integration (with standard Django Model support) with `airtable-python-wrapper` as a dependency. It's made my work for that about 90,000x easier :)

**Comment by gtalarico** [comment]
Awesome to hear. Happy to accept contributions of any type.

I started a new projects and thanks to you picked wagtail. 
It's shaping up pretty well `learn-wagtail` has been a very valuable resource!

**Comment by KalobTaulien** [comment]
That's amazing! 🎉 

Im going to close this ""issue"" since this thread isnt really an issue at all :P
