### ISSUE TITLE
422 client error

### ISSUE THREAD

**Issue by JasonCrowe** [gtalarico/airtable-python-wrapper#8]
I am getting a 422 error when trying to insert a dictionary into Airtable. I get the same error is I use json.dumps to convert the dict into a json document.

The error goes away if I change the numbers in the dict into strings, but I don't think that should be necessary for json formatting.

```
{u'RowPointer': '17B42935-5002-4E97-B86C-35275F278E8F',
 u'base_style': u'11BAGK',
 u'country_origin': u'CN',
 u'description': u'ASST KIDS SUNGLASSES IN BAG12 PER INNER9',
 u'family_code': u'ACC',
 u'fourth_category': u'Z MISC',
 u'inventory_level': 110.0,
 u'item': u'11BAGK-K-WE-1',
 u'item_size': u'K',
 u'licensee_mark': None,
 u'plan_code': u'KID',
 u'product_code': u'TG-700-08',
 u'stat': u'A',
 u'unit_weight': 0.6,
 u'upc': u'072264110276',
 u'weight_units': u'KG'}
```

Any ideas or resources I can review?

**Comment by JasonCrowe** [comment]
The data is in a pandas dataframe, so to get around this issue I am converting columns to strings with the following code:

```
for c in df.columns:
    df[c] = df[c].astype(str)
```

**Comment by gtalarico** [comment]
Are you saying you cannot dump that dictionary as a Json string?

As for the 422, that's usually due to a mismatch between your data types, and the airtable column names and column types.

**Comment by JasonCrowe** [comment]
Okay, thank you. 

I was able to fix my Airtable formats, so they accept the numbers. 

Thanks for your help!

**Comment by gtalarico** [comment]
Happy to help
If you haven't yet, be sure to take a look at the official docs at https://airtable.com/api
