### ISSUE TITLE
Client Error: Unprocessable Entity for url

### ISSUE THREAD

**Issue by aneeshpanoli** [gtalarico/airtable-python-wrapper#80]
While using batch insert I got the following error.

`requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/app4FKBWUILUmUsE1/table13 (Decoded URL) [Error: {'type': 'INVALID_REQUEST_BODY', 'message': 'Could not parse request body'}]
`

I spent a lot of time digging around thinking it was a `single quote` error. 
In my case, I had a few `nan` in the values field.

It would be nice to have a check for `nan`s.
Thanks!

**Comment by gtalarico** [comment]
The airtable client has no way of knowing the types on your airtable base - afaik airtable does not offer this functionality yet. Therefore, it's up to the user to verify the data types and values provided.

**Comment by aneeshpanoli** [comment]
Sounds fair, thanks!
