### ISSUE TITLE
Reslove linked records

### ISSUE THREAD

**Issue by pmsoltani** [gtalarico/airtable-python-wrapper#81]
First of all, big thanks for your efforts!

Now, when retrieving records, the Airtable API returns a list of record IDs for the "linked record" fields. Can you add a feature to optionally resolve those IDs with the values of their respective primary fields?

Essentially, turning this:

```javascript
[
  {
    "createdTime": "2019-07-31T10:24:21.000Z",
    "fields": {
      "First Name": "Sam",
      "Last Name": "Smith",
      "Favorite Colors": [
        "recYoe2AZgYhZTU9E", "rec9Qs7MakwU7Q2bg"
      ]
    },
    "id": "rec06OuBOPIJ0gC8k"
  }
]
```

into this:

```javascript
[
  {
    "createdTime": "2019-07-31T10:24:21.000Z",
    "fields": {
      "First Name": "Sam",
      "Last Name": "Smith",
      "Favorite Colors": [
        "Red", "Black"
      ]
    },
    "id": "rec06OuBOPIJ0gC8k"
  }
]
```

In the above example, there are two tables with a base: `Names` & `Colors`.

**Comment by gtalarico** [comment]
Hi - I don't think there is a way to do this because the returned value does not include the view name.

**Comment by pmsoltani** [comment]
Yeah... I was just going over the Airtable API docs. I think you're right. I might submit an issue to them. In the mean how do you think I should proceed? Extend the class to work like this?

```python
airtable = Airtable('base_key', 'table_name', a_new_arg={'Field Name1': 'Table Name1', ...})
```

**Comment by genelee9-vc** [comment]
I was reading through this discussion b/c I have a question along similar lines. I don't necessarily need to have the translations beforehand as I am doing it downstream in a BI tool, but I do require those unique record ids Airtable generates in the background. So when I run this code:

from airtable import Airtable
import pandas as pd

base_key = 'TABLE BASE KEY'
table_name = 'TABLE'
airtable = Airtable(base_key,table_name,api_key='MY API KEY')
print(airtable)

records = airtable.get_all(fields=['Name','Count'],sort=[("Count",'desc')])
    
df= pd.DataFrame.from_records((r['fields'] for r in records))
df

I'd like to be able to bring in that Airtable unique id (e.g. rec#########) along with my specified fields in my converted pandas table. And it seems like a simple thing to remedy, but I cannot figure this out! I am somewhat fresh to Python so bear with me.

Any advice? Thanks for all of this btw, it's been a huge help!

**Comment by pmsoltani** [comment]
@genelee9-vc 
If I understand you correctly, your question isn't related to "linked records" and you just want to show the record id as a separate column along with other fields.

In that case, replace the line below in your code:

```python3
df= pd.DataFrame.from_records(({**r['fields'], 'id': r['id']} for r in records))
```

Basically, you would be constructing a new dictionary from each one in the `records` list. The `**r['fields']` part, unpacks the `fields` dictionary inside each record. You can google "python dictionary unpacking" to find out more.

**Comment by genelee9-vc** [comment]
@pmsoltani
This is exactly what I wanted to accomplish. Thank you so much!
