### ISSUE TITLE
How to get more than 100 rows using Airtable API using offest?

### ISSUE THREAD

**Issue by Krishangi** [gtalarico/airtable-python-wrapper#85]
I am really new to the Airtable API and for some reason getting data from the API this way did not work.
``
from airtable import airtable

at = airtable.Airtable('Base_Key', 'Airtable_Key')
records = at.get_all(maxRecords=20)
``

> Error : AttributeError: 'Airtable' object has no attribute 'get_all'

But I got it working this way -
``
import_ json
import requests
get_url = ‘https://api.airtable.com/v0/BASE_ID/TABLE_NAME’
get_headers = {
‘Authorization’: ‘Bearer API_KEY’ }

Response = requests.get(get_url, headers=get_headers)
Response_Table = Response.json()
``
However, this fetches only the first 100 records and am reading about offset and pagination but I am unable to figure how to incorporate it into this code.
I am using Python 3 on Jupyter Notebook

Thank you for the time!

**Comment by gtalarico** [comment]
see library docs for `get_all` or `get_iter`
