### ISSUE TITLE
Cannot get the wrapper to work. 

### ISSUE THREAD

**Issue by iampatterson** [gtalarico/airtable-python-wrapper#87]
When I try to run your code I get this problem before I do anything. 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-6f721098dfff> in <module>
      5 import os
      6 from pprint import pprint
----> 7 from airtable import Airtable
      8 import pandas as pd
      9 

ImportError: cannot import name 'Airtable' from 'airtable' (/opt/tljh/user/lib/python3.7/site-packages/airtable/__init__.py)

Tried everything, still no joy.  I know it is a noob problem, but for the life of me I can't figure it out.   Pip list is the following. 

ackage                 Version   
----------------------- ----------
airtable                0.3.1     
airtable-python-wrapper 0.13.0    
alembic                 1.4.2     
asn1crypto              0.24.0    
async-generator         1.10      
attrs                   19.3.0    
backcall                0.1.0     
bleach                  3.1.5     
certifi                 2020.4.5.2
certipy                 0.1.3     
cffi                    1.12.3    
chardet                 3.0.4     
conda                   4.8.1     
conda-package-handling  1.3.11    
cryptography            2.7       
cycler                  0.10.0    
decorator               4.4.2     
defusedxml              0.6.0     
entrypoints             0.3       
idna                    2.8       
importlib-metadata      1.6.1     
ipykernel               5.3.0     
ipython                 7.15.0    
ipython-genutils        0.2.0     
ipywidgets              7.5.1     
jedi                    0.17.0    
Jinja2                  2.11.2    
joblib                  0.15.1    
json5                   0.9.5     
jsonschema              3.2.0     
jupyter-client          6.1.3     
jupyter-core            4.6.3     
jupyterhub              1.0.0     
jupyterlab              1.2.16    
jupyterlab-server       1.1.5     
kiwisolver              1.2.0     
libarchive-c            2.8       
Mako                    1.1.3     
MarkupSafe              1.1.1     
matplotlib              3.2.1     
mistune                 0.8.4     
nbconvert               5.6.1     
nbformat                5.0.6     
nbgitpuller             0.7.2     
nbresuse                0.3.4     
notebook                6.0.3     
nteract-on-jupyter      2.1.3     
numpy                   1.18.5    
oauthlib                3.1.0     
packaging               20.4      
pamela                  1.0.0     
pandas                  1.0.4     
pandocfilters           1.4.2     
parso                   0.7.0     
pexpect                 4.8.0     
pickleshare             0.7.5     
pip                     19.1.1    
prometheus-client       0.8.0     
prompt-toolkit          3.0.5     
ptyprocess              0.6.0     
pycosat                 0.6.3     
pycparser               2.19      
Pygments                2.6.1     
pyOpenSSL               19.0.0    
pyparsing               2.4.7     
pyrsistent              0.16.0    
PySocks                 1.7.0     
python-dateutil         2.8.1     
python-editor           1.0.4     
pytz                    2020.1    
pyzmq                   19.0.1    
requests                2.22.0    
ruamel-yaml             0.15.46   
scikit-learn            0.23.1    
scipy                   1.4.1     
seaborn                 0.10.1    
Send2Trash              1.5.0     
setuptools              41.0.1    
six                     1.12.0    
sklearn                 0.0       
SQLAlchemy              1.3.17    
terminado               0.8.3     
testpath                0.4.4     
threadpoolctl           2.1.0     
tornado                 5.1.1     
tqdm                    4.32.1    
traitlets               4.3.3     
urllib3                 1.24.2    
wcwidth                 0.2.4     
webencodings            0.5.1     
wheel                   0.33.4    
widgetsnbextension      3.5.1     
zipp                    3.1.0

**Comment by gtalarico** [comment]
Likely an import clash. 
Do you have a file or folder named airtable?
If not, try importing 'airtable' in an interactive shell and explore the object to see whats being imported

**Comment by iampatterson** [comment]
I will apologize in advance. I am a data scientist, not a programmer.  
 I don't have a file or folder named Airtable.    All I am trying to do is import an Airtable into a dataframe.  If I manage to get "get_all" to work,  is it going to do what I need?.  Is there an easier way?. 

I don't think I can manage to do what you asked regarding "exploring the object"   At this point I would pay money to get it done.

**Comment by iampatterson** [comment]
I read this article below, but the "get_all" doesn't work, so I am in trouble. 

https://github.com/gtalarico/airtable-python-wrapper/issues/51

**Comment by gtalarico** [comment]
Get all is a method of airtable class Instances and thats the only method you will need to create a panda DF from airtable api response

Are you using python 3?

**Comment by iampatterson** [comment]
Yes python 3.

**Comment by iampatterson** [comment]
I tried both on my jupyterhub server, as well as a local conda install.

**Comment by iampatterson** [comment]
Locally I have this problem

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-c08af65e9f2d> in <module>
      9 base_key = 'base key'
     10 table_name = 'test'
---> 11 airtable = airtable.Airtable(base_key, table_name, api_key=os.environ['key'])
     12 print(airtable)

/Applications/anaconda3/lib/python3.7/os.py in __getitem__(self, key)
    676         except KeyError:
    677             # raise KeyError with the original key value
--> 678             raise KeyError(key) from None
    679         return self.decodevalue(value)
    680 

KeyError: 'key'

**Comment by iampatterson** [comment]
Using the following I get a response from airtable, so I know my keys are working

at = airtable.Airtable ("base key", "API key")

**Comment by iampatterson** [comment]
dir(airtable) gets me the following. 
['Airtable',
 'AirtableAuth',
 'AirtableParams',
 'IS_IPY',
 'OrderedDict',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'posixpath',
 'quote',
 'requests',
 'sys',
 'time',
 'unquote']

**Comment by iampatterson** [comment]
Sorry, somehow I got it to work.  I eliminated the "os.environ" before the API key and away we go.  Any idea as to why?  I have yet to do this on my Jupyterhub server.  But at least I have it running locally.

**Comment by iampatterson** [comment]
I was reading up about os.environ. It seems like it would be the thing to do.  I am not sure how it works without it.

**Comment by gtalarico** [comment]
Environ is pythons object to access the systems environment variables. The library can pull the api key from the environment or you can explicitly pass it as an argument. Up to you. 

Details on authentication and are the link below. 
I suggest you read these docs and the source include here:
https://airtable-python-wrapper.readthedocs.io/en/master/authentication.html

I am closing this now since these are not library issues but just generic python questions that are better suited for stackoverflow

But feel free to ask other questions and I will help if I can.

**Comment by iampatterson** [comment]
Thanks for your help. After re-reading the authentication docs, as well as the .os docs  I understand what you are doing and also what I did wrong.  I will fork this and change that bit of code to be explicit.  There are others who have had the same problem as me on Stack. There is little to no reference on the Airtable forums.   Neither have a solution posted, so I will cover those off as well. 

Thanks again for your help. 

Kind Regards
Michael
