### ISSUE TITLE
422 error when batch deleting 1 record

### ISSUE THREAD

**Issue by cuchoi** [gtalarico/airtable-python-wrapper#94]
Hi! Thanks for this amazing wrapper.

I think the recent update to support the limit of ten records ids broke the ability to batch delete one record. Is this expected? 
Before I used to do:
```
record_ids = [record["id"] for record in records]
airtable.batch_delete(record_ids)
```
But I started getting the following error:
```
requests.exceptions.HTTPError: ('422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/<app_id>/Reporting?records=recXXXXXXXXXXX', '422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/<app_id>/Reporting?records=recXXXXXXXXXXX [Error: {\'type\': \'INVALID_RECORDS\', \'message\': \'"records" must be an array of up to 10 record IDs.\'}]')
```
Now I am doing
```
record_ids = [record["id"] for record in records]
if len(record_ids) == 1:
      connection_airtable.delete(record_ids[0])
else:
      connection_airtable.batch_delete(record_ids)
```
Not a big deal but I thought it might be useful to report this issue.

**Comment by KNWR** [comment]
Hi, thanks for creating the library. Wanted to confirm I'm finding the same error.

**Comment by gtalarico** [comment]
thank you for confirming this. I will try to take a look at this when I can, in the meantime if someone has the time to investigate this and prepare a PR fix I am happy to review and merge it

**Comment by KNWR** [comment]
cc @gtalarico we can probably close this?

**Comment by gtalarico** [comment]
yep thanks!
