### ISSUE TITLE
ImportError: cannot import name 'Airtable' from 'airtable'

### ISSUE THREAD

**Issue by KNWR** [gtalarico/airtable-python-wrapper#98]
Hi,

I'm trying to set up the project locally so I can contribute (to fix the 422 error when batch deleting 1 record).

I git cloned the repo, and in the repo ran:
```
python3.8 -m venv ./venv
source ./venv/bin/activate
pip install -r requirements-dev.txt
pytest

```
which gave a ModuleNotFoundError:

```
ImportError while loading conftest '/Users/KWar/GitHub/airtable-python-wrapper/tests/conftest.py'.
tests/conftest.py:9: in <module>
    from airtable import Airtable
E   ModuleNotFoundError: No module named 'airtable'
```

UPDATE:

I solved this by running `pip install .`, based on this stackoverflow answer: [https://stackoverflow.com/a/1472014](https://stackoverflow.com/a/1472014).

Will leave this in case anyone else who's less familiar with python projects finds it useful.

**Comment by gtalarico** [comment]
Did you solve this @KNWR ?

**Comment by gtalarico** [comment]
> It looks like I'm not the only one who's had this issue.
Just answer it  - likely name clash
https://stackoverflow.com/a/64036806/4411196


> I solved this by running pip install .
Thanks for sharing this. I used to have a `CONTRIBUTING.md` file with contribution instructions but not sure what happened with it! 🤷 

I think `pip install -e .` should work - though I think `-e` should be used to ensure it's linked.
But I think the more proper way is  `python setup.py develop`

https://stackoverflow.com/a/45863466/4411196
